### ISSUE TITLE
専用organization作ってそこに移管？

### ISSUE THREAD

**Issue by xuwei-k** [septeni-original/sbt-dao-generator#113]
🤔

**Comment by tkawachi** [comment]
PR いろいろありがとうございます。
社内での方針は固まっていない状況ですが、 @xuwei-k さんも活用されてるのでしょうか？

**Comment by xuwei-k** [comment]
@xuwei-k さんが副業する予定の某企業で使ってるらしい、けど、その社内で使ってる具合というか今後どうするのか(どの程度使っていくのか)の詳細は不明、みたいな

**Comment by xuwei-k** [comment]
こっちの社内の状況がどうであれ flinters 社で全然メンテする予定がなさそうなら、いずれにせよ専用org作って移管してもらった方がメンテはしやすそう・・・？ 🤔 
こっちの社に移管かforkも不可能ではないだろうけど、それはそれで結局メンテする人が退職したり、その社で使わなくなったりすると、結局似たような問題が発生する可能性があるので、
そういう意味では(最初だけ面倒だけど)専用orgの方が、コミッター増減するのも、管理が面倒じゃないだろうし

**Comment by tkawachi** [comment]
そうですね。専用 org 作りましょうか。

**Comment by tkawachi** [comment]
https://github.com/sbt-dao-generator/sbt-dao-generator に移しました。関係の深そうな人を organization の owner にしています。

**Comment by xuwei-k** [comment]
> その社内で使ってる具合というか今後どうするのか(どの程度使っていくのか)の詳細は不明

今後も使っていくことになるかも
